name: ci

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:

jobs:
  compile_and_run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Compile code
        run: npm run compile
      - name: Run test coverage
        run: npm run coverage
